/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArticleCard: typeof import('./src/components/ArticleCard.vue')['default']
    ArticleCardInCreation: typeof import('./src/components/ArticleCardInCreation.vue')['default']
    ArticleRender: typeof import('./src/components/ArticleRender.vue')['default']
    ArtText: typeof import('./src/components/ArtText.vue')['default']
    BackIcon: typeof import('./src/components/BackIcon.vue')['default']
    Carousel: typeof import('./src/components/Carousel.vue')['default']
    CollapseSelector: typeof import('./src/components/CollapseSelector.vue')['default']
    Creator: typeof import('./src/components/Creator.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    Gallery: typeof import('./src/components/Gallery.vue')['default']
    HeaderNav: typeof import('./src/components/HeaderNav.vue')['default']
    More: typeof import('./src/components/more.vue')['default']
    MusicPlayer: typeof import('./src/components/MusicPlayer.vue')['default']
    MusicUpload: typeof import('./src/components/MusicUpload.vue')['default']
    MusicView: typeof import('./src/components/MusicView.vue')['default']
    MusicViewInMore: typeof import('./src/components/MusicViewInMore.vue')['default']
    NoData: typeof import('./src/components/common/NoData.vue')['default']
    PersonnalInfo: typeof import('./src/components/PersonnalInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
    TypeContainer: typeof import('./src/components/TypeContainer.vue')['default']
    Video: typeof import('./src/components/Video.vue')['default']
    VideoUpload: typeof import('./src/components/VideoUpload.vue')['default']
    VideoView: typeof import('./src/components/VideoView.vue')['default']
  }
}
